# Ajuste para o banco desejado.
# Exemplo MySQL:
# db.url=jdbc:mysql://localhost:3306/revisao_jdbc?useSSL=false&serverTimezone=UTC
# db.user=root
# db.password=isadora

# Exemplo PostgreSQL:
# db.url=jdbc:postgresql://localhost:5432/revisao_jdbc
# db.user=postgres
# db.password=isadora

db.url=jdbc:postgresql://localhost:5432/revisao_jdbc
db.user=postgres
db.password=isadora
