package viewer;


import controller.FuncoesUteis;
import controller.GerInterGrafica;
import controller.GerenciadorDominio;
import controller.PacienteTableModel;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import model.Paciente;
import model.Vacina;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carol
 */
public class FrmCadastroVacinacao extends javax.swing.JFrame {
    
    private final PacienteTableModel pacTableModel = new PacienteTableModel();
    private final GerenciadorDominio gerDom = GerInterGrafica.getInstance().getGerDominio();
    private Paciente pacientePesquisado = null;
    
    public FrmCadastroVacinacao() {
        initComponents();
        configurarTelaInicial();
        configurarAcoesBotoes();
        configurarPesquisaPorId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVacinas = new javax.swing.ButtonGroup();
        jPopupResumo = new javax.swing.JPopupMenu();
        jMenuItemInserir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtDose1 = new javax.swing.JRadioButton();
        rbtDose2 = new javax.swing.JRadioButton();
        Vacina = new javax.swing.JLabel();
        cmbVacinas = new javax.swing.JComboBox<>();
        rbtOutras = new javax.swing.JRadioButton();
        btnInserir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResumo = new javax.swing.JTable();
        painelData1 = new javax.swing.JPanel();
        Data1 = new javax.swing.JLabel();
        txtDataDose1 = new javax.swing.JTextField();
        painelData2 = new javax.swing.JPanel();
        Data2 = new javax.swing.JLabel();
        txtDataDose2 = new javax.swing.JTextField();
        btnPesqTodos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItemInserir.setText("jMenuItem1");
        jMenuItemInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPopupResumo.add(jMenuItemInserir);

        jMenuItem1.setText("jMenuItem1");
        jPopupResumo.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Nacional de Vacinação");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Agenda Vacinação");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        Nome.setText("Nome");

        CPF.setText("CPF");

        jLabel2.setText("ID");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(CPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Vacina"));

        grupoVacinas.add(rbtDose1);
        rbtDose1.setMnemonic('1');
        rbtDose1.setText("COVID - 1ª dose");
        rbtDose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDose1ActionPerformed(evt);
            }
        });

        grupoVacinas.add(rbtDose2);
        rbtDose2.setMnemonic('2');
        rbtDose2.setText("COVID - 2ª dose");
        rbtDose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDose2ActionPerformed(evt);
            }
        });

        Vacina.setText("Nome da Vacina");

        grupoVacinas.add(rbtOutras);
        rbtOutras.setMnemonic('O');
        rbtOutras.setText("Outras");
        rbtOutras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOutrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtDose1)
                        .addGap(18, 18, 18)
                        .addComponent(rbtDose2)
                        .addGap(18, 18, 18)
                        .addComponent(rbtOutras))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Vacina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbVacinas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtDose1)
                    .addComponent(rbtDose2)
                    .addComponent(rbtOutras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vacina)
                    .addComponent(cmbVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));

        tabResumo.setModel(pacTableModel);
        tabResumo.setName(""); // NOI18N
        jScrollPane1.setViewportView(tabResumo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelData1.setBorder(javax.swing.BorderFactory.createTitledBorder("1ª Dose"));

        Data1.setText("Data");

        txtDataDose1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataDose1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelData1Layout = new javax.swing.GroupLayout(painelData1);
        painelData1.setLayout(painelData1Layout);
        painelData1Layout.setHorizontalGroup(
            painelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelData1Layout.createSequentialGroup()
                .addComponent(Data1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataDose1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        painelData1Layout.setVerticalGroup(
            painelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data1)
                    .addComponent(txtDataDose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelData2.setBorder(javax.swing.BorderFactory.createTitledBorder("2ª Dose"));

        Data2.setText("Data");

        txtDataDose2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataDose2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelData2Layout = new javax.swing.GroupLayout(painelData2);
        painelData2.setLayout(painelData2Layout);
        painelData2Layout.setHorizontalGroup(
            painelData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelData2Layout.createSequentialGroup()
                .addComponent(Data2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataDose2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelData2Layout.setVerticalGroup(
            painelData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelData2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data2)
                    .addComponent(txtDataDose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPesqTodos.setText("Pesquisar todos");

        jButton1.setText("Pesq. 2ª dose");

        jButton2.setText("Pesq. por Vacina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnInserir)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesqTodos))
                            .addComponent(painelData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(painelData2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInserir)
                        .addComponent(btnPesqTodos)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtDose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDose1ActionPerformed
        
        // Preencher Combo com as vacinas da COVID
        carregarVacinasPorTipo(1);
        
        painelData1.setVisible(true);
        painelData2.setVisible(true);
        txtId.setEditable(false);
        txtId.setText("");
        pacientePesquisado = null;
        jtxtNome.setText("");
        txtCPF.setText("");
    }//GEN-LAST:event_rbtDose1ActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
            if (rbtDose2.isSelected()) {
                inserirSegundaDose();
            } else {
                inserirNovoPaciente();
            }

            limparCampos();
            pesquisarTodos();
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir dados: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbtOutrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOutrasActionPerformed
        
        // Preencher Combo com as OUTRAS vacinas
        carregarVacinasPorTipo(2);
        
        painelData1.setVisible(true);
        painelData2.setVisible(false);
        txtId.setEditable(false);
        txtId.setText("");
        txtDataDose1.setText("");
        txtDataDose2.setText("");
        pacientePesquisado = null;
        jtxtNome.setText("");
        txtCPF.setText("");
        
    }//GEN-LAST:event_rbtOutrasActionPerformed

    private void rbtDose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDose2ActionPerformed
        
        // Preencher Combo com as vacinas da COVID
        carregarVacinasPorTipo(1);
        
        painelData1.setVisible(false);
        painelData2.setVisible(true);
        txtId.setEditable(true);
        txtDataDose1.setText("");
    }//GEN-LAST:event_rbtDose2ActionPerformed

    private void txtDataDose2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataDose2FocusLost
        String strData1 = txtDataDose1.getText();
        String strData2 = txtDataDose2.getText();
         
        if ( ! ("".equals(strData1)) && !("".equals(strData2)) ) {
            // Data 1 NÃO VAZIA
            
            Calendar data1 = new GregorianCalendar();
            Calendar data2 = new GregorianCalendar();
            
            try {
                data1.setTime( FuncoesUteis.strToDate(strData1) );
                data2.setTime( FuncoesUteis.strToDate(strData2) );

                Calendar min = (Calendar) data1.clone();
                Calendar max = (Calendar) data1.clone();

                String vacina = cmbVacinas.getSelectedItem().toString();

                if ( vacina.equals("CoronaVac") ) {
                    // Entre 14 e 28
                    min.add(Calendar.DAY_OF_MONTH, 14);    
                    max.add(Calendar.DAY_OF_MONTH, 28);    
                } else if ( vacina.equals("AstraZeneca") ) {
                    // Entre 77 e 84
                    min.add(Calendar.DAY_OF_MONTH, 77);    
                    max.add(Calendar.DAY_OF_MONTH, 84);    
                } else if ( vacina.equals("Pfizer") ) {
                    // Entre 21 e 30
                    min.add(Calendar.DAY_OF_MONTH, 21);    
                    max.add(Calendar.DAY_OF_MONTH, 30);    
                } 

                if ( data2.after(max) ) {
                    JOptionPane.showMessageDialog(this, "A data da 2ª dose deve ser MENOR que " + FuncoesUteis.dateToStr(max.getTime()), "Intervalo da 2ª dose", JOptionPane.ERROR_MESSAGE );                
                } else if ( data2.before(min) ) {
                    JOptionPane.showMessageDialog(this, "A data da 2ª dose deve ser MAIOR que " + FuncoesUteis.dateToStr(min.getTime()), "Intervalo da 2ª dose", JOptionPane.ERROR_MESSAGE );
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data inválida!", "Conversão de data", JOptionPane.ERROR_MESSAGE );
            }
        } else {
            // SOMENTE VALIDAR A DATA 2
            try {
                if ( ! "".equals(strData2) ) {
                    FuncoesUteis.strToDate(strData2);
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data da 2ª dose inválida!\n" + strData2, "Conversão de data", JOptionPane.ERROR_MESSAGE );
                txtDataDose2.requestFocusInWindow();
            }
            
        }
        
        
    }//GEN-LAST:event_txtDataDose2FocusLost

    private void txtDataDose1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataDose1FocusLost
        String strData1 = txtDataDose1.getText();
         
        Calendar data1 = new GregorianCalendar();
        Calendar data2 = new GregorianCalendar();
        try {
            data1.setTime( FuncoesUteis.strToDate(strData1) );
            data2.setTime( data1.getTime()  );

            String vacina = cmbVacinas.getSelectedItem().toString();

            if ( vacina.equals("CoronaVac") ) {
                data2.add(Calendar.DAY_OF_MONTH, 21);    // 14 a 28
                txtDataDose2.setText( FuncoesUteis.dateToStr(data2.getTime() ) );
            } else if ( vacina.equals("AstraZeneca") ) {
                data2.add(Calendar.DAY_OF_MONTH, 80);   // 77 a 84
                txtDataDose2.setText( FuncoesUteis.dateToStr(data2.getTime() ) );        
            } else if ( vacina.equals("Pfizer") ) {
                data2.add(Calendar.DAY_OF_MONTH, 21);   // 21 a 30
                txtDataDose2.setText( FuncoesUteis.dateToStr(data2.getTime() ) );   
            } else {
                txtDataDose2.setText("");   
            }
        
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data da 1ª dose inválida!\n" + strData1, "Conversão de data", JOptionPane.ERROR_MESSAGE );
            txtDataDose1.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtDataDose1FocusLost

    private void configurarTelaInicial() {
        rbtDose1.setSelected(true);
        txtId.setEditable(false);
        carregarVacinasPorTipo(1);
        painelData1.setVisible(true);
        painelData2.setVisible(true);
        pesquisarTodos();
    }

    private void configurarAcoesBotoes() {
        btnPesqTodos.addActionListener(evt -> pesquisarTodos());
        jButton1.addActionListener(evt -> pesquisarSegundaDose());
        jButton2.addActionListener(evt -> pesquisarPorVacina());
    }

    private void configurarPesquisaPorId() {
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisarPacientePorIdDigitado();
            }
        });
    }

    private void pesquisarPacientePorIdDigitado() {
        if (!rbtDose2.isSelected()) {
            return;
        }

        String idStr = txtId.getText().trim();

        if (idStr.isEmpty()) {
            pacientePesquisado = null;
            jtxtNome.setText("");
            txtCPF.setText("");
            return;
        }

        int idPaciente;
        try {
            idPaciente = Integer.parseInt(idStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID inválido.", "Pesquisa por ID", JOptionPane.ERROR_MESSAGE);
            pacientePesquisado = null;
            jtxtNome.setText("");
            txtCPF.setText("");
            return;
        }

        try {
            Paciente encontrado = gerDom.pesquisarPacientePorId(idPaciente);

            if (encontrado != null) {
                pacientePesquisado = encontrado;
                jtxtNome.setText(encontrado.getNomePaciente());
                txtCPF.setText(encontrado.getCpf());
            } else {
                pacientePesquisado = null;
                jtxtNome.setText("");
                txtCPF.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar paciente: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
            pacientePesquisado = null;
        }
    }

    private void carregarVacinasPorTipo(int tipoVacina) {
        try {
            cmbVacinas.removeAllItems();
            List<Vacina> vacinas = gerDom.pesquisarVacinasPorTipo(tipoVacina);
            for (Vacina vacina : vacinas) {
                cmbVacinas.addItem(vacina);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar vacinas: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Vacina getVacinaSelecionada() {
        Object selected = cmbVacinas.getSelectedItem();
        if (selected == null) {
            return null;
        }
        return (Vacina) selected;
    }

    private void inserirNovoPaciente() throws ParseException {
        String nome = jtxtNome.getText().trim();
        String cpf = txtCPF.getText().trim();
        String dataDose1Str = txtDataDose1.getText().trim();
        String dataDose2Str = txtDataDose2.getText().trim();

        if (nome.isEmpty()) {
            throw new RuntimeException("Informe o nome do paciente.");
        }
        if (!FuncoesUteis.isCPF(cpf)) {
            throw new RuntimeException("CPF inválido.");
        }

        Vacina vacina = getVacinaSelecionada();
        if (vacina == null) {
            throw new RuntimeException("Selecione uma vacina.");
        }

        if (dataDose1Str.isEmpty()) {
            throw new RuntimeException("Informe a data da 1ª dose.");
        }

        Date dataDose1 = FuncoesUteis.strToDate(dataDose1Str);
        Date dataDose2 = null;
        int precisaDose2 = 0;

        if (vacina.getQtdeDoses() > 1) {
            if (dataDose2Str.isEmpty()) {
                throw new RuntimeException("Informe a data da 2ª dose.");
            }
            dataDose2 = FuncoesUteis.strToDate(dataDose2Str);
            precisaDose2 = 1;
        }

        Paciente paciente = new Paciente();
        paciente.setNomePaciente(nome);
        paciente.setCpf(cpf);
        paciente.setDataDose1(dataDose1);
        paciente.setDataDose2(dataDose2);
        paciente.setPrecisaDose2(precisaDose2);
        paciente.setVacina(vacina);

        gerDom.inserirPaciente(paciente);
        JOptionPane.showMessageDialog(this, "Paciente inserido com sucesso.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
    }

    private void inserirSegundaDose() throws ParseException {
        String idStr = txtId.getText().trim();
        String dataDose2Str = txtDataDose2.getText().trim();

        if (idStr.isEmpty()) {
            throw new RuntimeException("Informe o ID do paciente para registrar a 2ª dose.");
        }

        int idPaciente;
        try {
            idPaciente = Integer.parseInt(idStr);
        } catch (NumberFormatException ex) {
            throw new RuntimeException("ID inválido.");
        }

        if (dataDose2Str.isEmpty()) {
            throw new RuntimeException("Informe a data da 2ª dose.");
        }

        if (pacientePesquisado == null || pacientePesquisado.getIdPaciente() != idPaciente) {
            throw new RuntimeException("Pesquise o paciente pelo ID antes de registrar a 2ª dose.");
        }

        Date dataDose2 = FuncoesUteis.strToDate(dataDose2Str);
        gerDom.registrarDose2(pacientePesquisado.getIdPaciente(), dataDose2);
        
        pacientePesquisado.setDataDose2(dataDose2);
        pacientePesquisado.setPrecisaDose2(0);

        JOptionPane.showMessageDialog(this, "2ª dose registrada com sucesso.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
    }

    private void pesquisarTodos() {
        try {
            pacTableModel.setLista(gerDom.listarPacientes());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar todos: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void pesquisarSegundaDose() {
        try {
            pacTableModel.setLista(gerDom.pesquisarPacientesDose2());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar 2ª dose: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void pesquisarPorVacina() {
        try {
            Vacina vacina = getVacinaSelecionada();
            if (vacina == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma vacina para pesquisar.", "Pesquisa", JOptionPane.WARNING_MESSAGE);
                return;
            }

            pacTableModel.setLista(gerDom.pesquisarPacientesPorVacina(vacina));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar por vacina: " + ex.getMessage(), "Banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparCampos() {
        txtId.setText("");
        jtxtNome.setText("");
        txtCPF.setText("");
        txtDataDose1.setText("");
        txtDataDose2.setText("");
        pacientePesquisado = null;
    }
  
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Data1;
    private javax.swing.JLabel Data2;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Vacina;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesqTodos;
    private javax.swing.JComboBox<Vacina> cmbVacinas;
    private javax.swing.ButtonGroup grupoVacinas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemInserir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupResumo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JPanel painelData1;
    private javax.swing.JPanel painelData2;
    private javax.swing.JRadioButton rbtDose1;
    private javax.swing.JRadioButton rbtDose2;
    private javax.swing.JRadioButton rbtOutras;
    private javax.swing.JTable tabResumo;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtDataDose1;
    private javax.swing.JTextField txtDataDose2;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
